openapi: 3.0.1
info:
  title: App Form Status
  description: APIs for App Form Status
  version: 1.0.0
paths:
  
  /appFormStatus/caseId:
    get:
      tags:
        - App Form Status
      summary:  Fetch an App Form Status
      description: Fetch an App Form Status
      operationId: fetchAppFormStatus
      parameters:
        - $ref: '#/components/parameters/caseId'
      responses:
        '200':
          $ref: '#/components/responses/FetchAppformstatusResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  
  /appFormStatus/{applicationFormStatusid}:
    post:
      tags:
        - App Form Status
      summary:  Create an App Form Status
      description: Create an App Form Status
      operationId: CreateAppFormStatus
      parameters:
        - $ref: '#/components/parameters/ApplicationFormStatusid'
      requestBody:
          $ref: '#/components/requestBodies/CreateAppFormStatusRequest'
      responses:
        '200':
          $ref: '#/components/responses/CreateAppFormStatusResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    FetchAppformstatusResponse:
      type: array
      properties:
        appFormStatusId: 
          type: number
          format: integer
        progress:
          type: number
          format: integer
    CreateAppFormStatusRequest:
      type: object
      properties:
        progress:
          type: number
          format: integer
    CreateAppFormStatusResponse:
      type: object
      properties: 
        ApplicationFormStatusid:
          type: number
          format: integer
        
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
    
  parameters:
    caseId:
      name: caseId
      in: query
      required: true
      schema:
        type: string
    ApplicationFormStatusid:
      name: ApplicationFormStatusid
      in: path
      required: true
      schema:
        type: string
        
  requestBodies:
    CreateAppFormStatusRequest:
        description: CreateAppFormStatusRequest
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/CreateAppFormStatusRequest'  
  responses:
    FetchAppformstatusResponse:
        description: fetchExecuetiveManagement
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/FetchAppformstatusResponse' 
    CreateAppFormStatusResponse:
        description: fetchExecuetiveManagement
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/CreateAppFormStatusResponse' 
        
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
