openapi: 3.0.1
info:
  title: Clead Performance 
  description:  clead Performance Metrics
  version: 11.0.0
paths:
  /clead/{doctorId}/listingWisePerformance/Retrieve:
    get:
      tags:
        - clead Performance
      summary: Get listing-wise performance metrics for a clead
      description: Returns listing-wise performance metrics for a specific clead
      operationId: getListingWisePerformance
      parameters:
        - $ref: '#/components/parameters/doctorId'
      responses:
        '200':
          $ref: '#/components/responses/RetrieveListingWisePerformanceResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /clead/{doctorId}/profilePagePerformance/Retrieve:
    get:
      tags:
        - clead Performance
      summary: Get profile page performance metrics for a clead
      description: Returns profile page performance metrics for a specific clead
      operationId: getProfilePagePerformance
      parameters:
        - $ref: '#/components/parameters/doctorId'
      responses:
        '200':
          $ref: '#/components/responses/RetrieveProfilePagePerformanceResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /clead/{doctorId}/status/Retrieve:
    get:
      tags:
        - clead Performance
      summary: Get status metrics for a doctor
      description: Returns status metrics for a specific clead
      operationId: getStatusMetrics
      parameters:
        - $ref: '#/components/parameters/doctorId'
      responses:
        '200':
          $ref: '#/components/responses/RetrieveStatusMetricsResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /clead/{doctorId}/leadSource/Retrieve:
    get:
      tags:
        - clead Performance
      summary: Get lead source metrics for a clead
      description: Returns lead source metrics for a specific clead
      operationId: getLeadSourceMetrics
      parameters:
        - $ref: '#/components/parameters/doctorId'
      responses:
        '200':
          $ref: '#/components/responses/RetrieveLeadSourceMetricsResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /clead/{doctorId}/overallLeads/Retrieve:
    get:
      tags:
        - clead Performance
      summary: Get overall leads metrics for a clead
      description: Returns overall leads metrics for a specific clead
      operationId: getOverallLeadsMetrics
      parameters:
        - $ref: '#/components/parameters/doctorId'
      responses:
        '200':
          $ref: '#/components/responses/RetrieveOverallLeadsMetricsResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    ListingWisePerformance:
      type: object
      properties:
        url:
          type: string
          description: The URL of the listing
        domestic:
          type: number
          description: Number of domestic patients
        International:
          type: number
          description: Number of international patients
        Hot:
          type: number
          description: Number of hot leads
        Warm:
          type: number
          description: Number of warm leads
        Cold:
          type: number
          description: Number of cold leads
        Valid:
          type: number
          description: Number of valid leads
        Invalid:
          type: number
          description: Number of invalid leads
        IP:
          type: number
          description: Number of in-patient leads
        OP:
          type: number
          description: Number of out-patient leads
        IP_Percentage:
          type: number
          description: Percentage of in-patient leads
        OP_Percentage:
          type: number
          description: Percentage of out-patient leads
        Total_Arrivals:
          type: number
          description: Total number of arrivals

    ProfilePagePerformance:
      type: object
      properties:
        Impressions:
          type: number
          description: Number of profile impressions
        Clicks:
          type: number
          description: Number of profile clicks
        Views:
          type: number
          description: Number of profile views
        Calls:
          type: number
          description: Number of calls received
        Enquiries:
          type: number
          description: Number of enquiries received

    StatusMetrics:
      type: object
      properties:
        In_Patient:
          type: number
          description: Number of in-patient cases (with percentage)
        Out_Patient:
          type: number
          description: Number of out-patient cases (with percentage)
        Invalid:
          type: number
          description: Number of invalid cases (with percentage)
        Closed:
          type: number
          description: Number of closed cases (with percentage)

    LeadSourceMetrics:
      type: object
      properties:
        Source:
          type: string
          description: The source of the lead
        count:
          type: number
          description: Number of leads from this source

    OverallLeadsMetrics:
      type: object
      properties:
        Users:
          type: number
          description: Number of users
        All_leads:
          type: number
          description: Total number of leads
        Hot_leads:
          type: number
          description: Number of hot leads
        Warm_leads:
          type: number
          description: Number of warm leads
        Cold_leads:
          type: number
          description: Number of cold leads

    HTTPError:
      type: object
      properties:
        status_code:
          type: integer
          format: int32
        status:
          type: string
        message:
          type: string

    RetrieveListingWisePerformanceResponse:
      type: object
      properties:
        ListingWisePerformance:
          $ref: '#/components/schemas/ListingWisePerformance'

    RetrieveProfilePagePerformanceResponse:
      type: object
      properties:
        ProfilePagePerformance:
          $ref: '#/components/schemas/ProfilePagePerformance'

    RetrieveStatusMetricsResponse:
      type: object
      properties:
        StatusMetrics:
          $ref: '#/components/schemas/StatusMetrics'

    RetrieveLeadSourceMetricsResponse:
      type: object
      properties:
        LeadSourceMetrics:
          $ref: '#/components/schemas/LeadSourceMetrics'

    RetrieveOverallLeadsMetricsResponse:
      type: object
      properties:
        OverallLeadsMetrics:
          $ref: '#/components/schemas/OverallLeadsMetrics'

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'

    RetrieveListingWisePerformanceResponse:
      description: ListingWisePerformance
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveListingWisePerformanceResponse'

    RetrieveProfilePagePerformanceResponse:
      description: ProfilePagePerformance
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveProfilePagePerformanceResponse'

    RetrieveStatusMetricsResponse:
      description: StatusMetrics
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveStatusMetricsResponse'

    RetrieveLeadSourceMetricsResponse:
      description: LeadSourceMetrics
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveLeadSourceMetricsResponse'

    RetrieveOverallLeadsMetricsResponse:
      description: OverallLeadsMetrics
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveOverallLeadsMetricsResponse'

  parameters:
    doctorId:
      name: doctorId
      in: path
      required: true
      style: simple
      schema:
        type: string
