openapi: 3.0.1
info:
  title: Current Account
  description: BIAN Service Domain Packaged Business Capability (PCB) | DDD Bounded Context Current Account (expanded with ISO200022)
  version: 12.0.1
servers:
- url: ' https://virtserver.swaggerhub.com/BIAN-3/CurrentAccount/12.0.1'
paths:
   /CurrentAccountFacility/Initiate:
    post:
      tags:
          - CurrentAccountFacility
      summary: InCR Initiate A new current account
      description: InCR Initiate A new current account
      operationId: Initiate
      requestBody:
        $ref: '#/components/requestBodies/InitiateCurrentAccountFacilityRequest'
      responses:
        '200':
          $ref: '#/components/responses/InitiateCurrentAccountFacilityResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    CreateCurrentAccountRequest:
      type: object
      properties:
        ProductInstanceReference:
          type: object
          properties:
            CurrentAccountAgreement:
              type: string
        CurrentAccountNumber:
          type: object
          properties:
            Account:
              type: string
            Name:
              type: string
        CustomerReference:
          type: object
          properties:
            PartyReference:
              type: object
              properties:
                Identification:
                  type: string
        BankBranchLocationReference:
          type: object
          properties:
            BranchIdentification:
              type: object
              properties:
                Identifier:
                  type: string
            BranchAddress:
              type: object
              properties:
                AddressType:
                  type: string
                  format: string
                  enum:
                    - Postal Address
                    - GeolocationAddress
                    - LatitudeAddress
                    - LongitudeAddress
                    - ElectronicAddress"
                Address:
                  type: string
            BranchName:
              type: string
        AccountType:
          type: string
          format: string
          enum:
            - CurrentAccount
            - CreditAccount
            - VostroAcount
            - NostroAccount
            - PaymentAccount
            - SettlementAccount
            - SavingAccount
            - CashAccount
            - LoanAccount
        AccountCurrency:
          type: string
        AccountDateType:
          type: string
          format: date
          enum: 
            - OpeningDate
            - ClosingDate
            - BlockingDate
            - MaturityDate
            - LiveDate
        AccountDate:
          type: string
        CurrentAccountProductName:
          type: string
        CurrentAccountProductType:
          type: string
          format: string
          enum:
            - BusinessCurrentAccount
            - PersonalCurrentAccount
    CreateCurrentAccountResponse:
      type: object
      properties:
        ProductInstanceReference:
          type: object
          properties:
            CurrentAccountAgreement:
              type: string
        CurrentAccountNumber:
          type: object
          properties:
            Account:
              type: string
            Name:
              type: string
        CustomerReference:
          type: object
          properties:
            PartyReference:
              type: object
              properties:
                Identification:
                  type: string
        BankBranchLocationReference:
          type: object
          properties:
            BranchIdentification:
              type: object
              properties:
                Identifier:
                  type: string
            BranchAddress:
              type: object
              properties:
                AddressType:
                  type: string
                  format: string
                  enum:
                    - Postal Address
                    - GeolocationAddress
                    - LatitudeAddress
                    - LongitudeAddress
                    - ElectronicAddress"
                Address:
                  type: string
            BranchName:
              type: string
        AccountType:
          type: string
          format: string
          enum:
            - CurrentAccount
            - CreditAccount
            - VostroAcount
            - NostroAccount
            - PaymentAccount
            - SettlementAccount
            - SavingAccount
            - CashAccount
            - LoanAccount
        AccountCurrency:
          type: string
        AccountDateType:
          type: string
          format: date
          enum: 
            - OpeningDate
            - ClosingDate
            - BlockingDate
            - MaturityDate
            - LiveDate
        AccountDate:
          type: string
        CurrentAccountProductName:
          type: string
        CurrentAccountProductType:
          type: string
          format: string
          enum:
            - BusinessCurrentAccount
            - PersonalCurrentAccount
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
  requestBodies:
    InitiateCurrentAccountFacilityRequest:
      description: CurrentAccountFacilityInitiate
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateCurrentAccountRequest'
  responses:
    InitiateCurrentAccountFacilityResponse:
        description: fetchAccountUser
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/CreateCurrentAccountResponse'
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
