openapi: 3.0.1
info:
  title: Doctor Performance API
  description: APIs for Doctor Performance Metrics
  version: 1.0.0
paths:
  /doctor/{doctorId}/listing-wise-performance:
    get:
      tags:
        - Doctor Performance
      summary: Get listing-wise performance metrics for a doctor
      description: Returns listing-wise performance metrics for a specific doctor
      operationId: getListingWisePerformance
      parameters:
        - name: doctorId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Listing-wise performance metrics retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListingWisePerformance'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /doctor/{doctorId}/profile-page-performance:
    get:
      tags:
        - Doctor Performance
      summary: Get profile page performance metrics for a doctor
      description: Returns profile page performance metrics for a specific doctor
      operationId: getProfilePagePerformance
      parameters:
        - name: doctorId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Profile page performance metrics retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfilePagePerformance'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /doctor/{doctorId}/status:
    get:
      tags:
        - Doctor Performance
      summary: Get status metrics for a doctor
      description: Returns status metrics for a specific doctor
      operationId: getStatusMetrics
      parameters:
        - name: doctorId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Status metrics retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusMetrics'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /doctor/{doctorId}/lead-source:
    get:
      tags:
        - Doctor Performance
      summary: Get lead source metrics for a doctor
      description: Returns lead source metrics for a specific doctor
      operationId: getLeadSourceMetrics
      parameters:
        - name: doctorId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lead source metrics retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeadSourceMetrics'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /doctor/{doctorId}/overall-leads:
    get:
      tags:
        - Doctor Performance
      summary: Get overall leads metrics for a doctor
      description: Returns overall leads metrics for a specific doctor
      operationId: getOverallLeadsMetrics
      parameters:
        - name: doctorId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Overall leads metrics retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OverallLeadsMetrics'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    ListingWisePerformance:
      type: object
      properties:
        url:
          type: string
          description: The URL of the listing
        domestic:
          type: number
          description: Number of domestic patients
        International:
          type: number
          description: Number of international patients
        Hot:
          type: number
          description: Number of hot leads
        Warm:
          type: number
          description: Number of warm leads
        Cold:
          type: number
          description: Number of cold leads
        Valid:
          type: number
          description: Number of valid leads
        Invalid:
          type: number
          description: Number of invalid leads
        IP:
          type: number
          description: Number of in-patient leads
        OP:
          type: number
          description: Number of out-patient leads
        IP_Percentage:
          type: number
          description: Percentage of in-patient leads
        OP_Percentage:
          type: number
          description: Percentage of out-patient leads
        Total_Arrivals:
          type: number
          description: Total number of arrivals

    ProfilePagePerformance:
      type: object
      properties:
        Impressions:
          type: number
          description: Number of profile impressions
        Clicks:
          type: number
          description: Number of profile clicks
        Views:
          type: number
          description: Number of profile views
        Calls:
          type: number
          description: Number of calls received
        Enquiries:
          type: number
          description: Number of enquiries received

    StatusMetrics:
      type: object
      properties:
        In_Patient:
          type: number
          description: Number of in-patient cases (with percentage)
        Out_Patient:
          type: number
          description: Number of out-patient cases (with percentage)
        Invalid:
          type: number
          description: Number of invalid cases (with percentage)
        Closed:
          type: number
          description: Number of closed cases (with percentage)

    LeadSourceMetrics:
      type: array
      items:
        type: object
        properties:
          Source:
            type: string
            description: The source of the lead
          count:
            type: number
            description: Number of leads from this source

    OverallLeadsMetrics:
      type: object
      properties:
        Users:
          type: number
          description: Number of users
        All_leads:
          type: number
          description: Total number of leads
        Hot_leads:
          type: number
          description: Number of hot leads
        Warm_leads:
          type: number
          description: Number of warm leads
        Cold_leads:
          type: number
          description: Number of cold leads

    HTTPError:
      type: object
      properties:
        status_code:
          type: integer
          format: int32
        status:
          type: string
        message:
          type: string

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
