openapi: 3.0.1
info:
  title: Shareholder
  description: APIs for Shareholder
  version: 1.0.0
paths:
  /shareholders:
    post:
      tags:
        - Shareholder
      summary: Create a new Shareholder
      operationId: createShareholderList
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShareholderRequest'
      responses:
        '200':
          description: Create a new shareholder
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/ShareholderId'
                  
  /shareholder/search:
    get:
      tags:
        - Shareholder
      summary: Search Shareholder by corporate
      operationId: search
      parameters:
        - name: corporateName
          in: query
          description: corporate to search for
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of shareholders matching the search criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Shareholder'
components:
  schemas:
    Shareholder:
      type: object
      properties:
        shareholderId: 
          type: string
        shareholderEntity:
          type: string
        shareholderName_Value:
          type: number
        name: 
          type: string
        shareholdingPercent:
          type: number
        entityStatus:
          type: string
        corporate: 
          type: object
          properties:
                    name:
                      type: string
                    accountid:
                      type: string
    ShareholderId:
      type: object
      properties: 
         shareholderId: 
          type: string
    
    ShareholderRequest:
      type: object
      properties:
        corporate: 
          type: string
        shareholderName_Contact: 
          type: string
        shareholderName_Account:
          type: string
        shareholdingPercent:
          type: number
        entityStatus:
          type: string
        shareholderEntity:
          type: string

          
        