openapi: 3.0.1
info:
  title: User Management
  description: 'This service domain handles user management operations including retrieving user information and adding new users.'
  version: 11.0.0
servers:
  - url: https://dev.aairavx.com/api
paths:
  '/users/getusers/Retrieve':
    get:
      tags:
        - BQ - UserManagement
      summary: ReBQ Retrieve details about users
      description: ReBQ Retrieve details about users
      operationId: RetrieveUsers
      responses:
        '200':
          $ref: '#/components/responses/RetrieveUsersResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/users/Initiate':
    post:
      tags:
        - BQ - UserManagement
      summary: InBQ Initialize user creation
      description: InBQ Initialize user creation
      operationId: InitiateUserCreation
      requestBody:
        $ref: '#/components/requestBodies/InitiateUserRequest'
      responses:
        '200':
          $ref: '#/components/responses/InitiateUserResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    UserFacility:
      type: object
      properties:
        Title:
          type: string
          description: "The title of the user"
        created_on:
          type: string
          format: date
          description: "The creation date of the user record"
        Status:
          type: string
          description: "The current status of the user"
        No_of_APIs:
          type: integer
          description: "Number of APIs the user has access to"
        UserType:
          type: string
          enum: 
            - Admin
            - Regular
            - Guest
        EntitlementOptionSetting:
          type: string
        RestrictionOptionSetting:
          type: string
    UserManagement:
      type: object
      properties:
        OperationType:
          type: string
        UserDetails:
          type: string
        OperationDescription:
          type: string
    Users:
      type: array
      items:
        type: object
        properties:
          Title:
            type: string
          UserType:
            type: string
          OperationDescription:
            type: string
          UserDetails:
            type: string
          created_on:
            type: string
            format: date
          Status:
            type: string
          No_of_APIs:
            type: integer
    UserFacilityResponse:
      type: object
      properties:
        OperationReference:
          type: string
        PositionLimitValue:
          type: string
        DateType:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
    InitiateUserResponse:
      type: object
      properties:
        UserFacilityResponse:
          $ref: '#/components/schemas/Users'
    InitiateUserRequest:
      type: object
      properties:
        UserFacility:
          $ref: '#/components/schemas/Users'
        UserManagement:
          $ref: '#/components/schemas/Users'
    RetrieveUsersResponse:
      type: object
      properties:
        Users:
          $ref: '#/components/schemas/Users'
  requestBodies:
    InitiateUserRequest:
      description: InitiateUser
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateUserRequest'
      required: true
  responses:
    RetrieveUsersResponse:
      description: allUsers
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveUsersResponse'
    InitiateUserResponse:
      description: userOperation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateUserResponse'
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
