openapi: 3.0.1
info:
  title: User Management 
  description: managing users
  contact:
    name: BIAN
    url: https://bian.org
  version: 11.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /users/{userId}/Retrieve:
    get:
      tags:
        - CR - Users
      summary: Get user by ID
      description: Returns user details for a specific user ID
      operationId: Retrieve
      parameters:
        - $ref: '#/components/parameters/userId'
      responses:
        '200':
          $ref: '#/components/responses/RetrieveUserResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /users/Initiate:
    post:
      tags:
        - CR - Users
      summary: Initiate a new user
      description: Initiate a new user with the provided details
      operationId: Initiate
      requestBody:
        $ref: '#/components/requestBodies/InitiateUserRequest'
      responses:
        '201':
          $ref: '#/components/responses/InitiateUserResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: integer
          format: int32
        status:
          type: string
        message:
          type: string
      description: Status Attributes

    RetrieveUserResponse:
      type: object
      properties:
        name:
          type: string
          description: The full name of the user
        mobileNumber:
          type: string
          description: The mobile number of the user
        email:
          type: string
          format: email
          description: The email address of the user
        role:
          type: string
          description: The role of the user

    InitiateUserRequest:
      type: object
      properties:
        fullName:
          type: string
          description: The full name of the user
        mobileNumber:
          type: string
          description: The mobile number of the user
        email:
          type: string
          format: email
          description: The email address of the user
        role:
          type: string
          description: The role of the user
        permissions:
          type: string
          description: The permissions assigned to the user

    InitiateUserResponse:
      type: object
      properties:
        fullName:
          type: string
          description: The full name of the user
        mobileNumber:
          type: string
          description: The mobile number of the user
        email:
          type: string
          format: email
          description: The email address of the user
        role:
          type: string
          description: The role of the user
        permissions:
          type: string
          description: The permissions assigned to the user

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InitiateUserResponse:
      description: InitiateUserResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateUserResponse'
    RetrieveUserResponse:
      description: RetrieveUserResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveUserResponse'

  parameters:
    userId:
      name: userId
      in: path
      required: true
      style: simple
      schema:
        type: string

  requestBodies:
    InitiateUserRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateUserRequest'
      required: true
