openapi: 3.0.1
info:
  title: Users Management
  description: "This service domain manages user accounts and their details."
  version: 1.0.0
servers:
  - url: https://dev.aairavx.com/api
paths:
  "/users/Initiate":
    post:
      tags:
        - BQ - Users
      summary: InBQ Initialize user creation
      description: InBQ Initialize user creation
      operationId: InitiateUserCreation
      requestBody:
        description: User creation request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InitiateUserRequest"
      responses:
        "200":
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InitiateUserResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: "#/components/responses/InternalServerError"
  "/getUsers/Retrieve":
    get:
      tags:
        - BQ - Users
      summary: ReBQ Retrieve details about all users
      description: ReBQ Retrieve details about all users
      operationId: RetrieveAllUsers
      responses:
        "200":
          description: List of users retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RetrieveUsersResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: "#/components/responses/InternalServerError"
components:
  schemas:
    Users:
      type: array
      items:
        type: object
        properties:
          Title:
            type: string
            description: "User's title/role"
          UserType:
            type: string
            description: "Type of user (Admin, Guest, etc.)"
          UserDetails:
            type: string
            description: "Additional user details"
          created_on:
            type: string
            format: date
            description: "Date of creation (YYYY-MM-DD)"
          Status:
            type: string
            description: "User status (Active, Inactive, Pending)"
          No_of_APIs:
            type: integer
            description: "Number of APIs user has access to"
    InitiateUserRequest:
      type: object
      properties:
        Title:
          type: string
          description: "User's title/role"
        UserType:
          type: string
          description: "Type of user (Admin, Guest, etc.)"
        UserDetails:
          type: string
          description: "Additional user details"
        created_on:
          type: string
          format: date
          description: "Date of creation (YYYY-MM-DD)"
        Status:
          type: string
          description: "User status (Active, Inactive, Pending)"
        No_of_APIs:
          type: integer
          description: "Number of APIs user has access to"
      required:
        - Title
        - UserType
        - Status
    InitiateUserResponse:
      type: object
      properties:
        UserReference:
          type: string
          description: "Unique reference ID for the created user"
        Status:
          type: string
          description: "Confirmation status of user creation"
    RetrieveUsersResponse:
      type: object
      properties:
        Users:
          type: array
          items:
            $ref: "#/components/schemas/Users"
    HTTPError:
      type: object
      properties:
        status_code:
          type: integer
          description: "HTTP status code"
        status:
          type: string
          description: "Error status"
        message:
          type: string
          description: "Detailed error message"
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"
    Unauthorized:
      description: Unauthorized access
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"
    Forbidden:
      description: Forbidden access
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"
    TooManyRequests:
      description: Too many requests
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"
