openapi: 3.0.1
info:
  title: User Management
  description: 'This service domain handles user management operations including retrieving user information and adding new users.'
  version: 11.0.0
servers:
  - url: https://virtserver.swaggerhub.com/BIAN-3/BIAN/UserManagement/11.0.0
paths:
  '/User/getUsers/Retrieve':
    get:
      tags:
        - BQ - UserManagement
      summary: ReBQ Retrieve details about all users
      description: ReBQ Retrieve details about all users
      operationId: RetrieveAllUsers
      responses:
        '200':
          $ref: '#/components/responses/RetrieveUsersResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    Users:
      type: array
      items:
        type: object
        properties:
          UserReference:
            type: string
            description: "\n"
          UserName:
            type: string
            description: "\n"
          UserDescription:
            type: string
            description: "\n"
          UserType:
            type: string
            description: "\n"
          UserStatus:
            type: string
            description: "\n"
          CreatedDate:
            type: string
            description: "\n"
            format: date
          No_of_APIs:
            type: integer
            description: "\n"

    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: "\n"
        status:
          type: string
          description: "\n"
        message:
          type: string
          description: "\n"

    RetrieveUsersResponse:
      type: object
      properties:
        Users:
          $ref: '#/components/schemas/Users'


  responses:

    RetrieveUsersResponse:
      description: Users retrieved successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveUsersResponse'

    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'

    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'

    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'

    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'

    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
