openapi: 3.0.1
info:
  title: User Management
  description: 'This service domain handles user management operations including retrieving user information and adding new users.'
  version: 11.0.0
servers:
  - url: https://dev.aairavx.com/api
paths:
  '/Users/getUsers/Retrieve':
    get:
      tags:
        - BQ - UserManagement
      summary: ReBQ Retrieve details about users
      description: ReBQ Retrieve details about users
      operationId: RetrieveUsers
      responses:
        '200':
          $ref: '#/components/responses/RetrieveUsersResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/Users/usersCreate/Initiate':
    post:
      tags:
        - BQ - UserManagement
      summary: InBQ Initialize user creation
      description: InBQ Initialize user creation
      operationId: InitiateUserCreation
      requestBody:
        $ref: '#/components/requestBodies/InitiateUserRequest'
      responses:
        '200':
          $ref: '#/components/responses/InitiateUserResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    Users:
      type: array
      items:
        type: object
        properties:
          Title:
            type: string
            description: "\n"
          UserType:
            type: string
            description: "\n"
          OperationDescription:
            type: string
            description: "\n"
          UserDetails:
            type: string
            description: "\n"
          created_on:
            type: string
            description: "\n"
            format: date
          Status:
            type: string
            description: "\n"
          No_of_APIs:
            type: integer
            description: "\n"
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: "\n"
        status:
          type: string
          description: "\n"
        message:
          type: string
          description: "\n"
    InitiateUserResponse:
      type: object
      properties:
        Users:
          $ref: '#/components/schemas/Users'
    InitiateUserRequest:
      type: object
      properties:
        Users:
          $ref: '#/components/schemas/Users'
    RetrieveUsersResponse:
      type: object
      properties:
        Users:
          $ref: '#/components/schemas/Users'
  requestBodies:
    InitiateUserRequest:
      description: InitiateUser
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateUserRequest'
      required: true
  responses:
    RetrieveUsersResponse:
      description: allUsers
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveUsersResponse'
    InitiateUserResponse:
      description: userOperation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateUserResponse'
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
  parameters:
    userid:
      name: userid
      in: path
      required: true
      schema:
        type: string
